### ISSUE TITLE
Slackbuild for Slackware updated

### ISSUE THREAD

**Issue by richarson** [zealdocs/zeal-packaging#24]
Hello, I'm about to upload a slackbuild for zeal 0.4.0 and I noticed that on https://zealdocs.org/download.html there's a mention and a link ponting to 14.1.

You should update those to point to 14.2, which is Slackware's latest version.

Thanks.

**Comment by trollixx** [comment]
Fixed, thanks for letting me know.

P.S. It's better to report issues with the website in https://github.com/zealdocs/zealdocs.github.io.

**Comment by richarson** [comment]
Thank you, and sorry for reporting here, didn't realize the website was also on GH :)

**Comment by trollixx** [comment]
@richarson btw, why https://slackbuilds.org/repository/14.2/development/zeal/ shows 0.1.1? That's super old and unsupported?

**Comment by richarson** [comment]
Lazyness on my part, basically :)

When I was finally about to update to 0.2.x, you released 0.3.x which had the search issues so I thought to wait for 0.4. It was a long wait :)

Now, I already submitted an update for 0.4.0 and it was approved (https://slackbuilds.org/ready/), but SBo usually updates the website closer to the weekend, so it'll still show 0.1.1 for now.

BTW, have you seen https://repology.org/metapackages/all/?search=zeal?
It shows 20141123 as the latest version...

I'll try to contact them to get it fixed, maybe you want to reach them too.

**Comment by trollixx** [comment]
Repology looks interesting. Thanks for pointing me to it. I usually use pkgs.org, but it's intended for different use cases I think.

That date-version is from the old times, before I took over the project. I'll also try to contact freshcode to get it removed completely.
